In [3]:
import numpy as np

d = 3 # dimension of the array

array = np.arange(1, 13) # create an array of integers from 1 to 12
array = array.reshape(d, d + 1) # reshape the array to be d x (d + 1)

print(array[d - 1, :],'\n') # Select row d - 1 (the last row)

print(array[:, d],'\n') # Select column d (the last column)

print(array[[0, 1], :],'\n') # Select rows 0 and 1 (the first two rows)



[ 9 10 11 12] 

[ 4  8 12] 

[[1 2 3 4]
 [5 6 7 8]] 

