In [4]:
import numpy as np # import numpy library as np

array_1 = np.array([[0, d], [m, 3]]) # create a 2-by-2 array of zeros and assign it to array_1
array_2 = np.array([[4, 2 * d], [2 * m, 7]]) # create a 2-by-2 array of ones and assign it to array_2

array_3 = np.vstack((array_1, array_2)) # Use vertical stacking to create the 4-by-2 array named array_3 with array_2 stacked on top of array_1.

array_4 = np.hstack((array_1, array_2)) # Use horizontal stacking to create the 2-by-4 array named array_4 with array_2 to the right of array_1.

array_5 = np.vstack((array_4, array_4)) # Use vertical stacking with two copies of array_4 to create a 4-by-4 array_5.

array_6 = np.hstack((array_3, array_3)) # Use horizontal stacking with two copies of array_3 to create a 4-by-4 array_6.

print(array_3) # 4-by-2 array_3
print('----------------') # separator
print(array_4) # 2-by-4 array_4
print('----------------') # separator
print(array_5) # 4-by-4 array_5
print('----------------')
print(array_6) # 4-by-4 array_6

[[0 2]
 [3 3]
 [4 4]
 [6 7]]
----------------
[[0 2 4 4]
 [3 3 6 7]]
----------------
[[0 2 4 4]
 [3 3 6 7]
 [0 2 4 4]
 [3 3 6 7]]
----------------
[[0 2 0 2]
 [3 3 3 3]
 [4 4 4 4]
 [6 7 6 7]]
